The crocodile told the monkey that he had a wife and that they lived on the other side of the river. 
So the generous monkey plucked many rose-apples and gave them to the crocodile for his wife. ... 
